### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by szfck** [szfck/codeJudger#1]
- [x] have a test framework for php
- [x] set up a website framework
- [x] list up the library needed to be include in the docker container
- [x] makefile
